In [1]:
# More data types

In [2]:
# Casting

In [5]:
# “Bigger” type wins in mixed-type operations
import numpy as np

In [6]:
np.array([1, 2, 3]) + 1.5

array([ 2.5,  3.5,  4.5])

In [7]:
# Assignment never changes the type!
a = np.array([1, 2, 3])
a.dtype
a[0] = 1.9
a

array([1, 2, 3])

In [8]:
# Forced casts
a = np.array([1.7, 1.2, 1.6])
b = a.astype(int)  # <-- truncates to integer
b

array([1, 1, 1])

In [9]:
# Rounding
a = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])
b = np.around(a)
c = np.around(a).astype(int)
c

array([1, 2, 2, 2, 4, 4])

In [10]:
# maskedarray: dealing with (propagation of) missing data
# For floats one could use NaN’s, but masks work for all type
x = np.ma.array([1, 2, 3, 4], mask=[0, 1, 0, 1])
y = np.ma.array([1, 2, 3, 4], mask=[0, 1, 1, 1])
x+y

masked_array(data = [2 -- -- --],
             mask = [False  True  True  True],
       fill_value = 999999)

In [11]:
# Masking versions of common functions
np.ma.sqrt([1, -1, 2, -2]) 
masked_array(data = [1.0 -- 1.41421356237... --],
             mask = [False  True False  True],
       fill_value = 1e+20)

SyntaxError: invalid syntax (<ipython-input-11-689ba9df92c7>, line 3)