In [3]:
# Elementwise operations
import numpy as np

In [4]:
# Basic operations
a = np.array([1, 2, 3, 4])
a+1

array([2, 3, 4, 5])

In [5]:
2**a

array([ 2,  4,  8, 16])

In [7]:
# All arithmetic operates elementwise
b = np.ones(4) + 1
a - b
a * b
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [8]:
# These operations are of course much faster than if you did them in pure python
a = np.arange(10000)
%timeit a + 1
l = range(10000)
%timeit [i+1 for i in l]

The slowest run took 5.68 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 7.23 µs per loop
1000 loops, best of 3: 373 µs per loop


In [9]:
# Array multiplication is not matrix multiplication
c = np.ones((3, 3))
c*c

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [10]:
# Note Matrix multiplication
c.dot(c)

array([[ 3.,  3.,  3.],
       [ 3.,  3.,  3.],
       [ 3.,  3.,  3.]])

In [11]:
# Exercise: Elementwise operations


In [13]:
# Try simple arithmetic elementwise operations: add even elements with odd elements
a=np.linspace(2,10,5)
b=np.linspace(2,11,5)
a+b

array([  4.  ,   8.25,  12.5 ,  16.75,  21.  ])

In [14]:
# Time them against their pure python counterparts using %timeit.
%timeit [i+1 for i in l]

1000 loops, best of 3: 411 µs per loop


In [17]:
# Generate:
[2**0, 2**1, 2**2, 2**3, 2**4]
a_j = 2^(3*j) - j
a_j

array([ 2,  0,  6,  4, 10])

In [18]:
# Other operations
# Comparisons
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b
a>b

array([False, False,  True, False], dtype=bool)

In [20]:
# Logical operations
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)
np.logical_and(a, b)

array([ True, False, False, False], dtype=bool)

In [23]:
# Transcendental functions
a = np.arange(5)
a
np.sin(a)
np.log(a)
np.exp(a)

C:\Anaconda\lib\site-packages\ipykernel\__main__.py:5: RuntimeWarning: divide by zero encountered in log


array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [25]:
# Transposition
a = np.triu(np.ones((3, 3)), 1)
a.T

array([[ 0.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  1.,  0.]])

In [26]:
# Basic reductions


In [27]:
# Computing sums

In [29]:
x = np.array([1, 2, 3, 4])
np.sum(x)
x.sum()

10

In [30]:
# Sum by rows and by columns
x = np.array([[1, 1], [2, 2]])
x.sum(axis=0) # columns (first dimension)
x.sum(axis=1) # rows (second dimension)
x[0, :].sum(), x[1, :].sum()

(2, 4)

In [31]:
# Other reductions
x = np.array([1, 3, 2])
x.min()
x.max()
x.argmin()
x.argmax()

1

In [32]:
# Logical operations
np.all([True, True, False])
np.any([True, True, False])

True

In [33]:
# Note Can be used for array comparisons
a = np.zeros((100, 100))
np.any(a != 0)
np.all(a == a)
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])
((a <= b) & (b <= c)).all()

True

In [34]:
# Statistics
x = np.array([1, 2, 3, 1])
y = np.array([[1, 2, 3], [5, 6, 1]])
x.mean()
np.median(x)
np.median(y, axis=-1)
x.std()

0.82915619758884995

In [35]:
# Worked Example: diffusion using a random walk algorithm

In [36]:
n_stories = 1000 # number of walkers
t_max = 200      # time during which we follow the walker

In [39]:
# We randomly choose all the steps 1 or -1 of the walk
t = np.arange(t_max)
steps = 2 * np.random.random_integers(0, 1, (n_stories, t_max)) - 1
np.unique(steps) # Verification: all steps are 1 or -1

array([-1,  1])

In [40]:
# We build the walks by summing steps along the time
positions = np.cumsum(steps, axis=1) # axis = 1: dimension of tim
sq_distance = positions**2


In [48]:
# We get the mean in the axis of the stories
mean_sq_distance = np.mean(sq_distance, axis=0)
import matplotlib as plt

In [49]:
#Plot the results

plt.figure(figsize=(4, 3))
plt.plot(t, np.sqrt(mean_sq_distance), 'g.', t, np.sqrt(t), 'y-')
plt.xlabel(r"$t$")
plt.ylabel(r"$\sqrt{\langle (\delta x)^2 \rangle}$")

AttributeError: 'module' object has no attribute 'figure'

In [50]:
# Broadcasting

In [51]:
# Basic operations on numpy arrays (addition, etc.) are elementwise
# This works on arrays of the same size.
# Nevertheless, It’s also possible to do operations on arrays of different sizes if Numpy can transform these arrays so that they all have the same size: this conversion is called broadcasting.

In [57]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
a
b = np.array([0, 1, 2])
b
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [58]:
a = np.ones((4, 5))
a[0] = 2  # we assign an array of dimension 0 to an array of dimension 1
a

array([[ 2.,  2.,  2.,  2.,  2.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [59]:
# An useful trick
a = np.arange(0, 40, 10)
a.shape
a = a[:, np.newaxis]  # adds a new axis -> 2D array
a.shape
a
a+b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [60]:
# Worked Example: Broadcasting

In [62]:
mileposts = np.array([0, 198, 303, 736, 871, 1175, 1475, 1544,
...        1913, 2448])
distance_array = np.abs(mileposts - mileposts[:, np.newaxis])
distance_array

array([[   0,  198,  303,  736,  871, 1175, 1475, 1544, 1913, 2448],
       [ 198,    0,  105,  538,  673,  977, 1277, 1346, 1715, 2250],
       [ 303,  105,    0,  433,  568,  872, 1172, 1241, 1610, 2145],
       [ 736,  538,  433,    0,  135,  439,  739,  808, 1177, 1712],
       [ 871,  673,  568,  135,    0,  304,  604,  673, 1042, 1577],
       [1175,  977,  872,  439,  304,    0,  300,  369,  738, 1273],
       [1475, 1277, 1172,  739,  604,  300,    0,   69,  438,  973],
       [1544, 1346, 1241,  808,  673,  369,   69,    0,  369,  904],
       [1913, 1715, 1610, 1177, 1042,  738,  438,  369,    0,  535],
       [2448, 2250, 2145, 1712, 1577, 1273,  973,  904,  535,    0]])

In [63]:
x, y = np.arange(5), np.arange(5)[:, np.newaxis]
distance = np.sqrt(x ** 2 + y ** 2)
distance

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  4.        ],
       [ 1.        ,  1.41421356,  2.23606798,  3.16227766,  4.12310563],
       [ 2.        ,  2.23606798,  2.82842712,  3.60555128,  4.47213595],
       [ 3.        ,  3.16227766,  3.60555128,  4.24264069,  5.        ],
       [ 4.        ,  4.12310563,  4.47213595,  5.        ,  5.65685425]])

In [64]:
plt.pcolor(distance)
plt.colorbar()

AttributeError: 'module' object has no attribute 'pcolor'

In [67]:
x, y = np.ogrid[0:5, 0:5]
x.shape, y.shape
distance = np.sqrt(x ** 2 + y ** 2)

In [68]:
# Array shape manipulation


In [69]:
# Flattening
a = np.array([[1, 2, 3], [4, 5, 6]])
a.ravel()
a.T
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [70]:
# Reshaping
a.shape
b = a.ravel()
b = b.reshape((2, 3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
# Adding a dimension
z = np.array([1, 2, 3])
z[:, np.newaxis]
z[np.newaxis, :]

array([[1, 2, 3]])

In [76]:
# Dimension shuffling

In [79]:
a = np.arange(4*3*2).reshape(4, 3, 2)
a.shape
a[0, 2, 1]
b = a.transpose(1, 2, 0)
b.shape
b[2, 1, 0]

5

In [80]:
# Resizing
a = np.arange(4)
a.resize((8,))
a

array([0, 1, 2, 3, 0, 0, 0, 0])

In [82]:
# Sorting data
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
# In-place sort
a.sort(axis=1)
# Sorting with fancy indexing
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
a[j]
#Finding minima and maxima
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)