### NumPy and SciPy


NumPy adds efficient vectors and matrices to Python that support vectorized operations

In [1]:
import numpy as np  # Idiomatic import

In [2]:
# Create a NumPy Array
A = np.array([1,1.5,2,2.5])
A

array([ 1. ,  1.5,  2. ,  2.5])

Unlike Python lists, all the values in a NumPy array have the same type. This allows NumPy to implement operations on vectors much more efficiently than Python's operations on lists.

In [3]:
# Vector operations
A = np.array([1.0, 2.0, 3.0])
B = np.array([7.0, 8.0, 9.0])
C = A + 3*B
C

array([ 22.,  26.,  30.])

#### Ex How would you do this operation with two lists [1.0,2.0,3.0] and [7.0, 8.0, 9.0]

Indexing for NumPy arrays works like for lists:

In [22]:
print(A[0])
print(A[1:3])
print(A[:2])
print(A[-1])

1.0
[ 2.  3.]
[ 1.  2.]
3.0


In [23]:
# Can apply operations to particular slices of an array
print(B)
B[1:3] += 1
print(B)

[ 7.  8.  9.]
[  7.   9.  10.]


There are various ways of creating vectors with some structure. Here are some examples:

In [24]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [25]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

A useful operation is to create a vector of n items regularly spaced in the interval [start,end]. That's what np.linspace is for:    

        np.linspace(start, end, n)

Sometimes all you want is the equivalent of range as a NumPy array. Use np.arange for that:

In [27]:
print(range(10))
print(np.arange(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 1 2 3 4 5 6 7 8 9]


#### Ex Using only NumPy operations, create a vector containing the numbers from 1 to 10. Then construct from there a vector with the squares from 12 to 102.

In [30]:
a=np.arange(1,11)
b=[i**2 for i in a]
b

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

Sometimes, it's more useful to space the elements equally in log-space:

In [31]:
# [base**start, base**(start+1), ..., base**(stop)]
np.logspace(1, 4, num=4, base=10)

array([    10.,    100.,   1000.,  10000.])

The np module has element-wise versions of most common math operations:

In [33]:
x = np.linspace(1.0, 4.0, 7)
print(np.exp(x))
print(np.sin(x))
print(np.max(x))
print(np.sum(x))

[  2.71828183   4.48168907   7.3890561   12.18249396  20.08553692
  33.11545196  54.59815003]
[ 0.84147098  0.99749499  0.90929743  0.59847214  0.14112001 -0.35078323
 -0.7568025 ]
4.0
17.5


In [34]:
# Can apply Boolean expressions element-wise..
print(x)
x % 2 == 1   # Which elements are odd?

[ 1.   1.5  2.   2.5  3.   3.5  4. ]


array([ True, False, False, False,  True, False, False], dtype=bool)

Element-wise Boolean expression, such as the one above, are useful for selecting the elements in an array with a certain property:

In [35]:
x[x % 2 == 1] 

array([ 1.,  3.])

This leads to very idiomatic expressions, such as this one:

In [36]:
np.sum(x[x % 2 == 1])  # Sum odd numbers in x

4.0

Of course, vectors have more interesting operations that simply element-wise math:

In [37]:
# Dot products
print(A)
print(B)
print(A.dot(B))
print(np.dot(A,B))  # Equivalent syntax, more symmetric

[ 1.  2.  3.]
[  7.   9.  10.]
55.0
55.0


#### Ex Calculate the dot product of A and B without using np.dot

In [42]:
c=[(i*j) for i in A for j in B]
c


[7.0, 9.0, 10.0, 14.0, 18.0, 20.0, 21.0, 27.0, 30.0]

In [43]:
# Cumulative sums and products
print(x)
print(x.cumsum())
print(x.cumprod())

[ 1.   1.5  2.   2.5  3.   3.5  4. ]
[  1.    2.5   4.5   7.   10.   13.5  17.5]
[   1.      1.5     3.      7.5    22.5    78.75  315.  ]


We can test if any or all of the elements of a vector have some property:

In [44]:
one_to_ten = np.arange(1,10+1)
np.all(one_to_ten > 0)

True

In [45]:
print(one_to_ten % 5 == 0)
np.any(one_to_ten % 5 == 0)  # Any multiples of five in there?

[False False False False  True False False False False  True]


True

Matrices are represented as 2D arrays

In [46]:
mat = np.array([
        [1., 2.],
        [3., 4.]
    ])
mat

array([[ 1.,  2.],
       [ 3.,  4.]])

Some simple matrices can be constructed directly, and are useful for building up more complicated operations:

In [47]:
# nxn Identity
I = np.eye(3)
I

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [48]:
# nxn zeros
Z = np.zeros((3,3))  # Pass shape as a tuple
Z

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [49]:
# A diagonal matrix
D = np.diag((1,2,3))  # Pass diagonal elements as a tuple
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

We can also build larger matrices by stacking smaller ones:

In [50]:
x = np.array([1., 2., 3.])
y = np.array([10., 20., 30.])
print np.hstack((x, y))  # [x y]
print np.vstack((x, y))  # / x \
                         # \ y /

[  1.   2.   3.  10.  20.  30.]
[[  1.   2.   3.]
 [ 10.  20.  30.]]


The shape of a matrix can be accessed with shape and changed with reshape():

In [52]:
A = np.array([[1,2,3], [4,5,6]])
print(A.shape)
print(A)
print(A.reshape((3,2)))
print(A.reshape((6,1)))

(2L, 3L)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [54]:
B = np.array([[1,2,3,4,5,6,7,8]])
B

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [55]:
B.shape

(1L, 8L)

In [56]:
B.reshape((8,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [57]:
print (B)
print(B.T)

[[1 2 3 4 5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


Indexing 2D arrays can be quite interesting. Here are some examples:

In [58]:
print(A[0,2])      # One element
print(A[0:1,1:2])  # Slicing in multiple dimensions
print(A[1,:])      # Whole 2nd row
print(A[:,2])      # Whole 3rd column

3
[[2]]
[4 5 6]
[3 6]


Normal matrix operations are there:

In [59]:
mat = np.array([
        [1., 2.],
        [3., 4.]
    ])

In [60]:
# Transpose
mat.T

array([[ 1.,  3.],
       [ 2.,  4.]])

In [61]:
# Trace
mat.trace()

5.0

In [62]:
# Matrix-vector product
v = np.array([5., 6.])
mat.dot(v)

array([ 17.,  39.])

In [63]:
# NOTE: `mat * v` is element-wise multiplication, with the elements of `v`
# broadcast (repeated) along the additional dimensions of `mat`.
# Broadcasting is an advanced topic that we won't cover, but be
# aware of the actual meaning of `mat * v`, which is not matrix-vector
# multiplication in the mathematical sense!
mat * v

array([[  5.,  12.],
       [ 15.,  24.]])

More advanced linear algebra operations are also implemented within the np.linalg module:

In [64]:
# Eigenstuff
eigvals, eigvecs = np.linalg.eig(mat)
print eigvals
print eigvecs[0]
print eigvecs[1]

[-0.37228132  5.37228132]
[-0.82456484 -0.41597356]
[ 0.56576746 -0.90937671]


In [65]:
# Determinants
np.linalg.det(mat)

-2.0000000000000004

In [66]:
# Matrix inverse
np.linalg.inv(mat)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [67]:
# Solve linear systems: M*x = v
print np.linalg.solve(mat, v)
print np.linalg.inv(mat).dot(v)

[-4.   4.5]
[-4.   4.5]


#### Ex With the help of IPython's autocomplete, calculate the Singular Value Decomposition USV of the matrix mat above. Combine the resulting matrices to verify that the decomposition is correct.

### Random Numbers

Plenty of common probability distributions are implemented in NumPy. You can probe information about these distributions, as well as sample random variates from them.    
We'll only scratch the surface here, in order to generate random data for our machine learning examples later today.

In [68]:
np.random.randint(100)  # Random integer in [0,100)

2

In [69]:
np.random.rand()  # Random number in [0,1)

0.47794782413004977

In [70]:
# Random 3x4 matrix, elements are uniformly sampled from [0,1)
np.random.rand(3,4)

array([[ 0.48214675,  0.58811747,  0.475873  ,  0.59457886],
       [ 0.65422851,  0.63406156,  0.01888331,  0.6281877 ],
       [ 0.28107556,  0.8299465 ,  0.78825796,  0.89838495]])

In [71]:
np.random.seed(1)
np.random.rand()

0.417022004702574

In [72]:
# Generators for lots of distributions
# There's more in scipy.random.distributions later today...
mu = 2.0
sigma = 1.5
print np.random.normal(mu, sigma)

0.796740742027


In [73]:
# Generate lots of numbers and check statistics on them
N = 1000
nums = np.random.normal(mu, sigma, N)
print nums[:10]  # Print first 10 for debugging
print 'Mean: %.2f, Std Dev %.2f' % (np.mean(nums), np.std(nums))

[ 1.32668329  0.34109739 -0.48177318 -1.54520291  3.70301802  0.4744788
  2.95604272  0.71014009  4.65891144  0.33445542]
Mean: 2.06, Std Dev 1.46


### SciPy


SciPy adds lots of operations common in scientific and engineering contexts. It's a huge library with lots to explore.    
Many SciPy functions are wrappers around heavy-duty Fortran libraries that have stood the test of time (e.g., LAPACK, MINPACK, ...)    

Again, we'll just scratch the surface here.

### Lambdas

We need to introduce one new Python concept before moving on: anonymous functions, or ***lambdas***.    
Lambdas are single-expression functions that you don't need to name explicitly. You typically use them when you want to pass a function as a parameter, instead of just data.    
Here's an example of a simple function, and its lambda equivalent:

In [74]:
def add_two_named(a,b):
    return a + b

add_two_lambda = (lambda a, b: a + b)

In [75]:
print(add_two_named(2,3))
print(add_two_lambda(2,3))

5
5


The general syntax is:    

lambda <param1>, <param2>, ...: <expression>    

Let's build an example where this is useful. The map built-in function in Python applies a function to each item in a list. Here's an example:

In [76]:
def f(x):
    return x**2

map(f, [1,2,3])

[1, 4, 9]

In [77]:
[f(1), f(2), f(3)]

[1, 4, 9]

In idiomatic Python, you'd usually use a list comprehension for this:

In [78]:
[x**2 for x in [1,2,3]]

[1, 4, 9]

But in other contexts (such as when using PySpark, which we'll talk about next week), the map way is more natural.    
In most cases, you'd pass in a simple function, so it's overkill (and less readable) to define a named function and then pass it by name. Instead, you'd do this:

In [79]:
map(lambda x: x**2, [1,2,3])

[1, 4, 9]

Another common use case is when sorting a list. Sometimes you want to sort not by the contents of the list, but by something closely related. For instance, here's one way of sorting a list of strings without regards to case:

In [80]:
fruits = ['BANANA', 'cherry', 'DaTE', 'apple']
print(sorted(fruits))  # Case-sensitive
print(sorted(fruits, key=lambda x: x.lower()))  # Case insensitive

['BANANA', 'DaTE', 'apple', 'cherry']
['apple', 'BANANA', 'cherry', 'DaTE']


#### Ex Sort the following list of full names by surname:

In [91]:
names = ["John Doe", "Mary Jane", "Jake Williamson", "Jack Ripper"]
print(sorted(names, key=lambda x: x[:1]))

['John Doe', 'Jake Williamson', 'Jack Ripper', 'Mary Jane']


In SciPy, it's common to apply operations on functions (e.g., integration, differentiation, root-finding, etc.). For small functions, you'd use a lambda. We'll see examples below.

### Numerical integration

In [111]:
from scipy import integrate

In [112]:
answer, err = integrate.quad(lambda x: 3 * x**2, 0, 1)  # [x**3]^1_0 == 1
print 'Answer: %f +/- %g' % (answer, err)

Answer: 1.000000 +/- 1.11022e-14


In [113]:
from scipy import Inf, exp
n = 2
integrate.dblquad(lambda t, x: exp(-x*t)/t**n, 0, Inf,
                  lambda t: 1, lambda t: Inf)

(0.499999999909358, 1.4640839512484866e-08)

### Optimization

In [114]:
def f(x):
    return 2 * x**2 + 5*x - 7

Without any further information, SciPy can find this function's minimum by astute trial and error (technically, using the Nelder-Mead algorithm). We need to provide a starting guess:

In [115]:
from scipy.optimize import minimize
x0 = np.array([0.0])
res = minimize(f, x0, method='nelder-mead',
               options={'xtol': 1e-8, 'disp': True})
print res

Optimization terminated successfully.
         Current function value: -10.125000
         Iterations: 38
         Function evaluations: 77
  status: 0
    nfev: 77
 success: True
     fun: -10.125
       x: array([-1.25])
 message: 'Optimization terminated successfully.'
     nit: 38


In [116]:
def f_prime(x):
    return 4*x + 5

In [117]:
x0 = np.array([0.0])
res = minimize(f, x0, method='BFGS', jac=f_prime,
               options={'disp': True})
print res

Optimization terminated successfully.
         Current function value: -10.125000
         Iterations: 1
         Function evaluations: 3
         Gradient evaluations: 3
   status: 0
  success: True
     njev: 3
     nfev: 3
 hess_inv: array([[1]])
      fun: -10.125
        x: array([-1.25])
  message: 'Optimization terminated successfully.'
      jac: array([ 0.])
